package sop_corba;


/**
* sop_corba/estudianteCllbckOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from requerimiento.idl
* domingo 7 de junio de 2015 12:19:24 PM COT
*/

public interface estudianteCllbckOperations 
{
  int puntos ();
  
  void puntos (int newPuntos);

  //establece la conexion entre los dos estudiantes, req: otroEstudiante debe haber iniciado el juego
  boolean chat (sop_corba.estudianteCllbck otroEstudiante);

  //actualiza la ventana del chat del estudiante
  void actualizar ();

  //envia un mensaje al chat
  boolean sendMessage (String mensaje);

  //obtiene un mensaje del chat
  String getMessage ();
} // interface estudianteCllbckOperations
