package sop_corba;



/**
* sop_corba/estudianteCllbckPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from requerimiento.idl
* domingo 7 de junio de 2015 12:19:24 PM COT
*/

public abstract class estudianteCllbckPOA extends org.omg.PortableServer.Servant
 implements sop_corba.estudianteCllbckOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_puntos", new java.lang.Integer (0));
    _methods.put ("_set_puntos", new java.lang.Integer (1));
    _methods.put ("chat", new java.lang.Integer (2));
    _methods.put ("actualizar", new java.lang.Integer (3));
    _methods.put ("sendMessage", new java.lang.Integer (4));
    _methods.put ("getMessage", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/estudianteCllbck/_get_puntos
       {
         int $result = (int)0;
         $result = this.puntos ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // sop_corba/estudianteCllbck/_set_puntos
       {
         int newPuntos = in.read_long ();
         this.puntos (newPuntos);
         out = $rh.createReply();
         break;
       }


  //establece la conexion entre los dos estudiantes, req: otroEstudiante debe haber iniciado el juego
       case 2:  // sop_corba/estudianteCllbck/chat
       {
         sop_corba.estudianteCllbck otroEstudiante = sop_corba.estudianteCllbckHelper.read (in);
         boolean $result = false;
         $result = this.chat (otroEstudiante);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  //actualiza la ventana del chat del estudiante
       case 3:  // sop_corba/estudianteCllbck/actualizar
       {
         this.actualizar ();
         out = $rh.createReply();
         break;
       }


  //envia un mensaje al chat
       case 4:  // sop_corba/estudianteCllbck/sendMessage
       {
         String mensaje = in.read_string ();
         boolean $result = false;
         $result = this.sendMessage (mensaje);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  //obtiene un mensaje del chat
       case 5:  // sop_corba/estudianteCllbck/getMessage
       {
         String $result = null;
         $result = this.getMessage ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/estudianteCllbck:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public estudianteCllbck _this() 
  {
    return estudianteCllbckHelper.narrow(
    super._this_object());
  }

  public estudianteCllbck _this(org.omg.CORBA.ORB orb) 
  {
    return estudianteCllbckHelper.narrow(
    super._this_object(orb));
  }


} // class estudianteCllbckPOA
