package sop_corba;


/**
* sop_corba/serviciosServidorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from requerimiento.idl
* domingo 7 de junio de 2015 12:19:24 PM COT
*/

public interface serviciosServidorOperations 
{

  //edita una palabra del diccionario con el codigo ingresado
  boolean modificarPalabra (String palabraAnterior, String palabraNueva, int codigo);

  //borra el diccionario con dicho codigo
  boolean borrarDiccionario (int codigo);

  //guarda la palabra en el diccionario con el codigo ingresado
  boolean guardarPalabra (String palabraGuardar, int codigo);

  //carga un diccionario desde la ubicacion ingresada y retorna el codigo del diccionario
  int generarDiccionario (String ubicacion);

  //obtiene una palabra de manera aleatorio entre todos los diccionarios
  String getPalabraAletoria ();

  //recibe una palabra y un codigo de palabra, retorna true si el codigo pertenece a la misma palabra ingresada
  boolean validarImagen (String palabra, int codigo);

  //obtiene la palabra que pertence al codigo ingresado
  String getPalabra (int codigo);

  //agrega un estudiante a la lista de estudiantes ingresados
  boolean addEstudiante (sop_corba.estudianteCllbck estudiante);

  //elimina un estudiante de la lista de estudiantes ingresados
  boolean deleteEstudiante (sop_corba.estudianteCllbck estudiante);

  //busca una palabra en ingles y retorna su significado en español
  String buscarPalabra (String palabraIngles);

  //establece una conexion entre los estudiantes a medida que se vayan agregado al juego
  void iniciarCompletaLetra (sop_corba.estudianteCllbck estudiante);
} // interface serviciosServidorOperations
