package sop_corba;


/**
* sop_corba/serviciosServidor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from requerimiento.idl
* domingo 7 de junio de 2015 12:19:24 PM COT
*/

public interface serviciosServidor extends serviciosServidorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface serviciosServidor
